version: "3.5"

services:
  tern_db:
    image: mysql:8.0
    container_name: tern_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tern_db
      MYSQL_USER: tern
      MYSQL_PASSWORD: secret
    ports:
      - "33066:3306"